ragflow:
  host: 0.0.0.0
  http_port: 9380
mysql:
  name: 'pulse_jshm'
  user: 'root'
  password: 'infini_rag_flow'
  host: '121.37.100.46'      # 改成宿主机ip
  port: 5455
  max_connections: 900
  stale_timeout: 300
minio:
  user: 'admin'
  password: 'infini_rag_flow'
  host: '121.37.100.46:9000'
es:
  hosts: 'http://121.37.100.46:1200'
  username: 'elastic'
  password: 'infini_rag_flow'
redis:
  db: 6
  password: 'infini_rag_flow'
  host: '121.37.100.46:6379'
sandbox:
  # host: '113.44.121.105'
  host: '121.37.100.46'
sso:
  url: 'http://121.37.100.46:36060/sso/getUserInfo'
update_Java_status:
  url: 'http://121.37.100.46:36060/client/dialog/runtime/publish'
java_response_url:
  url: 'http://121.37.100.46:36060/client/dialog/runtime/sso/getCommon'
update_conversation:
  url: 'http://121.37.100.46:36060/client/dialog/runtime/sso/updateConversation'
get_conversation:
  url: 'http://121.37.100.46:36060/client/dialog/runtime/sso/getWorkFlow'
list_agent_groups:
  url: 'http://121.37.100.46:36060/client/platform/group/list'
workspace:
  create_api: 'http://121.37.100.46:36060/agent/create'
  update_api: 'http://121.37.100.46:36060/agent/update'
  publish_api: 'http://121.37.100.46:36060/agent/publish'
  delete_api: 'http://121.37.100.46:36060/agent/delete'

